spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm
  datasource:
    url: jdbc:mysql://localhost:3306/lenaapi
    username: root
    password: Utermybest1
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    show-sql: true